[config]
schemaVersion = "0.0.1"

[package]
namespace = "loaforc"
name = "ShipVoiceCommands"
versionNumber = "1.5.0"
description = "A simple mod to add voice commands to the ship."
websiteUrl = "https://github.com/LoafOrc/ShipVoiceCommands"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
loaforc-VoiceRecognitionAPI = "1.2.0"
willis81808-LethalSettings = "1.2.1"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./bin/Release"
target = ""


[publish]
repository = "https://thunderstore.io"
communities = [ "riskofrain2", ]
[publish.categories]
riskofrain2 = [ "items", "skills", ]


